// Generates the vector half of the Memoria mark from the shared geometry:
//   app/public/favicon.svg          — the bare mark, transparent behind it
//   app/src/components/mark-path.ts — the same outline for the in-app logo
// Run: npm run icons (which also regenerates the PNG/ICO app icons).
//
// The favicon and the logo stay backgroundless on purpose. The squircle belongs
// to the APP ICON (taskbar, home screen, install prompt), where the tile is the
// product; a tab strip or a dark nav rail wants the mark alone so it sits on
// whatever is behind it.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { markAspect, markPath } from './mobius.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const app = join(here, '..');

// White-led, matching draw-icon.mjs. The mark reads white first and gold
// second; gold only arrives as the form falls away.
const GOLD_STOPS = [
  { offset: '0', color: '#ffffff' },
  { offset: '.62', color: '#fffaed' },
  { offset: '1', color: '#e8b45a' },
];

// The logo box is derived from the mark's own aspect instead of a hand-picked
// 44 × 24. A box of any other shape leaves slack on one axis, and slack is what
// lets a "centred" mark still look off-centre — markPath can only centre within
// the box it is given. Zero padding for the same reason: padding shrinks the
// drawing area on both axes equally, which re-introduces the mismatch.
const LOGO_HEIGHT = 24;
// A sliver of padding, because the Catmull-Rom CONTROL points sit a shade
// outside the curve they describe on the tightest turns. The fill never reaches
// them, but a renderer that clips to the viewBox would still be within its
// rights to trim them. The box grows to keep (W - 2p) / (H - 2p) equal to the
// mark's true aspect, so the padding costs no centring.
const LOGO_PADDING = 0.25;
const LOGO_WIDTH = Number((markAspect() * (LOGO_HEIGHT - LOGO_PADDING * 2) + LOGO_PADDING * 2).toFixed(2));

const faviconPath = markPath({ width: 64, height: 64, padding: 5, precision: 1 });
const logoPath = markPath({
  width: LOGO_WIDTH,
  height: LOGO_HEIGHT,
  padding: LOGO_PADDING,
  precision: 2,
});

const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="Memoria">
  <!-- Generated by app/scripts/gen-mark.mjs — edit the geometry in mobius.mjs. -->
  <!-- An infinity sign with a piece missing where it crosses itself: the loop's
       beginning/end, and the under-strand of the crossing, in one gap. -->
  <defs>
    <linearGradient id="void-gold" x1="0" y1="0" x2="1" y2="1">
${GOLD_STOPS.map((s) => `      <stop offset="${s.offset}" stop-color="${s.color}" />`).join('\n')}
    </linearGradient>
  </defs>
  <path fill="url(#void-gold)" d="${faviconPath}" />
</svg>
`;

const module = `// GENERATED by app/scripts/gen-mark.mjs — do not edit by hand.
// The Memoria mark: an infinity sign on a lemniscate of Bernoulli, with the piece at the
// crossing removed (see app/scripts/mobius.mjs for the geometry and why).
// Regenerate with \`npm run icons\`.

/** Outline of the mark, fitted exactly to its own ${LOGO_WIDTH} × ${LOGO_HEIGHT} bounding box. */
export const MARK_PATH =
  '${logoPath}';

export const MARK_WIDTH = ${LOGO_WIDTH};
export const MARK_HEIGHT = ${LOGO_HEIGHT};
`;

writeFileSync(join(app, 'public', 'favicon.svg'), favicon);
writeFileSync(join(app, 'src', 'components', 'mark-path.ts'), module);
console.log(`favicon.svg (${faviconPath.length} chars) and mark-path.ts (${logoPath.length} chars) written`);
