// Generates the vector half of the Void mark from the shared geometry:
//   app/public/favicon.svg          — the bare mark, transparent behind it
//   app/src/components/mark-path.ts — the same outline for the in-app logo
// Run: npm run icons (which also regenerates the PNG/ICO app icons).
//
// The favicon and the logo stay backgroundless on purpose. The squircle belongs
// to the APP ICON (taskbar, home screen, install prompt), where the tile is the
// product; a tab strip or a dark nav rail wants the mark alone so it sits on
// whatever is behind it.
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { markPath } from './mobius.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const app = join(here, '..');

const GOLD_STOPS = [
  { offset: '0', color: '#f5d68a' },
  { offset: '.55', color: '#e8b45a' },
  { offset: '1', color: '#c78a2e' },
];

const faviconPath = markPath({ width: 64, height: 64, padding: 5, precision: 1 });
const logoPath = markPath({ width: 44, height: 24, padding: 1, precision: 2 });

const favicon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" role="img" aria-label="Void">
  <!-- Generated by app/scripts/gen-mark.mjs — edit the geometry in mobius.mjs. -->
  <!-- A Möbius band with a piece missing where it crosses itself: the loop's
       beginning/end, and the under-strand of the crossing, in one gap. -->
  <defs>
    <linearGradient id="void-gold" x1="0" y1="0" x2="1" y2="1">
${GOLD_STOPS.map((s) => `      <stop offset="${s.offset}" stop-color="${s.color}" />`).join('\n')}
    </linearGradient>
  </defs>
  <path fill="url(#void-gold)" d="${faviconPath}" />
</svg>
`;

const module = `// GENERATED by app/scripts/gen-mark.mjs — do not edit by hand.
// The Void mark: a Möbius band traced along a lemniscate, with the piece at the
// crossing removed (see app/scripts/mobius.mjs for the geometry and why).
// Regenerate with \`npm run icons\`.

/** Outline of the mark, fitted to a 44 × 24 box. */
export const MARK_PATH =
  '${logoPath}';

export const MARK_WIDTH = 44;
export const MARK_HEIGHT = 24;
`;

writeFileSync(join(app, 'public', 'favicon.svg'), favicon);
writeFileSync(join(app, 'src', 'components', 'mark-path.ts'), module);
console.log(`favicon.svg (${faviconPath.length} chars) and mark-path.ts (${logoPath.length} chars) written`);
